import { NextRequest, NextResponse } from 'next/server';

const SUGGESTIONS = [
  'Oxytocin Acetate - 2mg',
  'PEG-MGF',
  'PT-141 5mg',
  'Selank 5mg',
  'Semaglutide 2mg',
  'Semax 10mg',
  'Sermorelin 2mg',
  'Snap-8 10mg',
  'Thymulin',
  'Tesamorelin 10 mg',
  'Tesamorelin 5 mg',
  'Tesamorelin 2 mg',
  'Thymosin alpha 1 - 5 MG',
  'TB-500 (Thymosin Œ≤4) 2mg',
  'Retatrutide 10 MG',
  'Adipotide - 10 MG',
  'NAD+ 500mg',
  'AOD-9604 2mg',
  'BPC 157 2mg',
  'Cagrilintide 5mg',
  'DSIP (Delta Sleep-Inducing Peptide) 5mg',
  'Epithalon 10mg',
  'GHK-Cu 50mg',
  'GHRP-2 - 2mg',
  'HCG 5,000iu',
  'Hexarelin 2mg',
  'IGF-1 LR3 1mg',
  'Kisspeptin-10 5mg',
  'MOTS-C 10mg',
  'Melanotan 2 10mg',
  'CJC-1295 with DAC 5mg',
  'Tirzepatide 5mg',
  'Tirzepatide 10 mg',
  'Tirzepatide 15 mg',
  'Tirzepatide 30 mg',
  'Tirzepatide 60 mg',
  'Thymosin alpha 1 - 10 MG',
  'TB-500 (Thymosin Œ≤4) 5mg',
  'TB-500 (Thymosin Œ≤4) 10mg',
  'Semaglutide 5mg',
  'Semaglutide 10mg',
  'Sermorelin 5mg',
  'SS-31 10mg',
  'SS-31 50mg',
  'HMG 75iu/vial',
  'Hexarelin 5mg',
  'GHRP-2 5mg',
  'GHK-Cu 100mg',
  'IGF-1 LR3 .1mg',
  'Ipamorelin 2mg',
  'Ipamorelin 5mg',
  'Ipamorelin 10mg',
  'CJC-1295 without DAC 2mg',
  'CJC-1295 without DAC 5mg',
  'CJC-1295 without DAC 10mg',
  'BPC 157 5mg',
  'BPC 157 10mg',
  'CJC-1295 WITH DAC 2mg',
  'Cagrilintide 10mg',
  'PT-141 10mg',
];

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const q = searchParams.get('q')?.toLowerCase() || '';
  if (!q) return NextResponse.json([]);
  const matches = SUGGESTIONS.filter(s => s.toLowerCase().includes(q)).slice(0, 8);
  return NextResponse.json(matches);
} 